(function(){
'use strict';
const C=window.GAME_CONTENT,E=window.ExodusEngine;let engine=null;const SAVE_KEY='exodus2149_save_v2';
const $=id=>document.getElementById(id);const esc=t=>String(t==null?'':t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const skillLabels={pilotage:'Pilotage',combat:'Combat',science:'Science',diplomacy:'Diplomatie',engineering:'Ingenierie',survival:'Survie'};const statLabels={physique:'Physique',reflexes:'Reflexes',intelligence:'Intelligence',technique:'Technique',presence:'Presence',volonte:'Volonte'};
function setImage(el,url){el.onerror=()=>{el.style.display='none';};el.style.display='block';el.src=url;}
function setOutcome(html){$('outcome').innerHTML=html;}
function preview(){const o=C.origins[$('originSelect').value],r=C.roles[$('roleSelect').value],t=C.traits[$('traitSelect').value];$('creationSummary').innerHTML='<strong>'+esc($('nameInput').value||'Commandant')+'</strong><br>'+esc(o.label)+' — '+esc(r.label)+'<br><br>'+esc(o.desc)+'<br>'+esc(r.desc)+'<br><br><span class="accent">'+esc(t.label)+'</span> : '+esc(t.desc);}
function init(){if(!C||!E){document.body.innerHTML='<pre>Erreur: content.js ou engine.js absent.</pre>';return;}engine=new E(C);window.exodusEngine=engine;fillSelect('originSelect',C.origins);fillSelect('roleSelect',C.roles);fillSelect('traitSelect',C.traits);$('versionLabel').textContent='v'+C.version;$('footerVersion').textContent=C.version;setImage($('startImage'),C.images.intro);wire();preview();toggleFeatureSections();$('bootStatus').textContent='Moteur pret';$('bootStatus').className='boot ok';}
function fillSelect(id,obj){$(id).innerHTML=Object.keys(obj).map(k=>'<option value="'+k+'">'+esc(obj[k].label)+'</option>').join('');}
function toggleFeatureSections(){[['missionSection','missions'],['factionSection','factions'],['researchSection','factions'],['colonySection','colony'],['outpostSection','galaxy']].forEach(([id,key])=>$(id).classList.toggle('hidden',!C.features[key]));}
function startGame(){engine.newGame({name:$('nameInput').value,origin:$('originSelect').value,role:$('roleSelect').value,trait:$('traitSelect').value,seed:$('seedInput').value||undefined});$('startScreen').classList.add('hidden');$('game').classList.remove('hidden');showIdleScene();render();}
function showIdleScene(){const s=engine.snapshot(),loc=C.locations.find(x=>x.id===s.locationId)||C.locations[0];setScene(loc.tag,loc.label,'Le secteur attend tes ordres. Choisis une action, une destination ou une mission.',C.images[loc.image]||C.images.intro);$('eventActions').innerHTML='';addExploreButton();}
function saveGame(show=true){try{localStorage.setItem(SAVE_KEY,JSON.stringify(engine.exportState()));if(show)setOutcome('<span class="good">Sauvegarde locale effectuee.</span>');}catch(e){if(show)setOutcome('<span class="warn">Sauvegarde impossible.</span>');}}
function loadGame(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw){$('bootStatus').textContent='Aucune sauvegarde';return;}if(engine.importState(JSON.parse(raw))){$('startScreen').classList.add('hidden');$('game').classList.remove('hidden');showIdleScene();render();}}catch(e){$('bootStatus').textContent='Sauvegarde invalide';}}
function setScene(tag,title,text,img){$('sceneTag').textContent=tag;$('sceneTitle').textContent=title;$('sceneText').textContent=text;setImage($('sceneImage'),img);}
function render(){const s=engine.snapshot();renderTop(s);renderCommander(s);renderShip(s);renderDestinations(s);renderCards(s);renderCrew(s);renderInventory(s);renderModules(s);renderCampaign(s);renderMissions(s);renderFactions(s);renderResearch(s);renderColony(s);renderOutposts(s);renderLog(s);renderRolls(s);renderCombat(s);renderButtons(s);window.dispatchEvent(new CustomEvent('exodus:render'));saveGame(false);if(engine.isDestroyed()){setOutcome('<span class="bad"><strong>L Asterion est detruit.</strong> Charge une sauvegarde ou recommence.</span>');document.querySelectorAll('#game button').forEach(b=>b.disabled=true);}}
function renderTop(s){$('topChips').innerHTML='<span class="chip">Jour '+s.day+'</span><span class="chip">Niv. '+s.commander.level+' / XP '+s.commander.xp+'</span><span class="chip">Credits '+s.ship.credits+'</span><span class="chip">Donnees '+s.ship.data+'</span><span class="chip">Rep '+s.ship.reputation+'</span><span class="chip">Destin '+s.destiny+'</span>'+(C.features.colony&&s.colony.founded?'<span class="chip">Colonie '+s.colony.population+'</span>':'');}
function renderCommander(s){$('commanderName').textContent=s.commander.name;$('commanderMeta').innerHTML=esc(s.commander.origin.label+' — '+s.commander.role.label+' — '+s.commander.trait.label)+'<br>PV '+s.commander.hp+'/'+s.commander.maxHp+(s.commander.injuries.length?'<br><span class="bad">Blessures: '+s.commander.injuries.map(esc).join(', ')+'</span>':'');$('statGrid').innerHTML=Object.keys(s.commander.stats).map(k=>'<div class="stat"><b>'+statLabels[k]+'</b><strong>'+s.commander.stats[k]+'</strong></div>').join('');$('skillGrid').innerHTML=Object.keys(s.commander.skills).map(k=>'<div class="skill-row"><span>'+skillLabels[k]+' <strong>'+s.commander.skills[k]+'</strong></span><button class="tiny-btn" data-skill="'+k+'" '+(s.commander.skillPoints<1?'disabled':'')+'>+</button></div>').join('');$('skillPoints').textContent=s.commander.skillPoints;$('skillGrid').querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>{const r=engine.upgradeSkill(b.dataset.skill);setOutcome(r.ok?'<span class="good">Competence amelioree.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();});}
function renderShip(s){$('hullText').textContent=s.ship.hull+'/'+s.ship.maxHull;$('shieldText').textContent=s.ship.shield+'/'+s.ship.maxShield;$('fuelText').textContent=s.ship.fuel+'/'+s.ship.maxFuel;$('suppliesText').textContent=s.ship.supplies+'/'+s.ship.maxSupplies;$('hullBar').style.width=(s.ship.hull/s.ship.maxHull*100)+'%';$('shieldBar').style.width=(s.ship.shield/s.ship.maxShield*100)+'%';$('fuelBar').style.width=(s.ship.fuel/s.ship.maxFuel*100)+'%';$('suppliesBar').style.width=(s.ship.supplies/s.ship.maxSupplies*100)+'%';$('repairBtn').textContent='Reparer (-'+engine.repairCost()+' cr.)';}
function renderDestinations(s){const box=$('destinationList');box.innerHTML='';engine.availableLocations().forEach(loc=>{const b=document.createElement('button');const cost=engine.travelCost(loc);b.className='soft';b.innerHTML='<strong>'+esc(loc.label)+'</strong><small>'+esc(loc.system)+' — '+cost+' carburant'+(loc.id===s.locationId?' — position actuelle':'')+'</small>';b.disabled=!!s.combat||!!s.mission||s.ship.fuel<cost;b.onclick=()=>{const r=engine.travel(loc.id);if(!r.ok){setOutcome('<span class="warn">'+esc(r.message)+'</span>');return render();}showEvent(r.event,r.location);render();};box.appendChild(b);});}
function renderCards(s){const box=$('cardList');box.innerHTML='';s.hand.forEach(card=>{const a=document.createElement('article');a.className='card'+(s.selectedCardUid===card.uid?' active':'');a.innerHTML='<h3>'+esc(card.name)+'</h3><p>'+esc(card.text)+'</p><div class="badges">'+card.tags.map(t=>'<span class="badge">'+esc(t)+'</span>').join('')+'</div>';a.onclick=()=>{engine.selectCard(card.uid);render();};box.appendChild(a);});}
function renderCrew(s){$('crewList').innerHTML=s.crew.map(m=>'<div class="crew"><strong>'+esc(m.name)+'</strong><small>'+esc(m.role)+' — '+esc(m.specialty)+'</small><div class="crew-meta"><span>PV '+m.hp+'/'+m.maxHp+'</span><span>Loy '+m.loyalty+'</span><span>Stress '+m.stress+'</span><span>Relation '+m.relation+'</span></div></div>').join('');}
function renderInventory(s){const box=$('inventoryList');box.innerHTML=C.items.map(item=>{const n=s.inventory[item.id]||0;return'<div class="module"><strong>'+esc(item.name)+' x'+n+'</strong><small>'+esc(item.desc)+'</small><button class="soft compact" data-use="'+item.id+'" '+(n<1?'disabled':'')+'>Utiliser</button></div>';}).join('');box.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{const r=engine.useItem(b.dataset.use);setOutcome(r.ok?'<span class="good">'+esc(r.item.name)+' utilise.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();});}
function renderModules(s){$('moduleList').innerHTML=C.modules.map(m=>'<div class="module"><strong>'+esc(m.name)+'</strong><small>'+esc(m.desc)+'</small><small>'+m.cost+' credits</small><button class="soft compact" data-module="'+m.id+'" '+(s.modules.includes(m.id)?'disabled':'')+'>'+(s.modules.includes(m.id)?'Installe':'Installer')+'</button></div>').join('');$('moduleList').querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>{const r=engine.installModule(b.dataset.module);setOutcome(r.ok?'<span class="good">Module installe.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();});}
function renderCampaign(s){$('campaignBox').innerHTML='<p>'+esc(engine.campaignText())+'</p><div class="progress-line"><span>Etape '+s.campaign.stage+'</span><span>Premier Contact '+(s.flags.firstContact?'oui':'non')+'</span></div>'+(s.campaign.complete?'<p class="good"><strong>OBJECTIF DE VERSION ACCOMPLI</strong></p>':'');}
function renderMissions(s){if(!C.features.missions)return;const box=$('missionList');if(s.mission){const def=C.missions.find(m=>m.id===s.mission.id);box.innerHTML='<div class="module"><strong>'+esc(def.title)+'</strong><small>Etape '+(s.mission.step+1)+'/'+def.steps.length+'</small><button id="abandonMission" class="danger compact">Abandonner</button></div>';$('abandonMission').onclick=()=>{engine.abandonMission();showIdleScene();render();};return;}const ms=engine.availableMissions();box.innerHTML=ms.length?ms.map(m=>'<div class="module"><strong>'+esc(m.title)+'</strong><small>'+esc(m.desc)+'</small><button class="soft compact" data-mission="'+m.id+'">Lancer (-2 fournitures)</button></div>').join(''):'<small class="muted">Aucune nouvelle mission disponible.</small>';box.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>{const r=engine.startMission(b.dataset.mission);if(r.ok){showEvent(r.event,{label:r.mission.title});}else setOutcome('<span class="warn">'+esc(r.message)+'</span>');render();});}
function renderFactions(s){if(!C.features.factions)return;const fbox=$('factionList');fbox.innerHTML=C.factions.filter(f=>!f.hiddenUntil||s.flags[f.hiddenUntil]).map(f=>'<div class="faction-row"><strong>'+esc(f.name)+'</strong><span>'+s.factions[f.id]+'</span></div>').join('');const cbox=$('contractList');cbox.innerHTML=C.contracts.map(c=>{const st=s.contracts[c.id],progress=st.start?engine.contractProgress(c,st):0;let action='';if(st.status==='available')action='<button data-accept="'+c.id+'" class="soft compact">Accepter</button>';if(st.status==='active')action='<small>Progression '+progress+'/'+c.goal+'</small>';if(st.status==='complete')action='<button data-claim="'+c.id+'" class="primary compact">Reclamer</button>';if(st.status==='claimed')action='<small class="good">Termine</small>';return'<div class="module"><strong>'+esc(c.name)+'</strong><small>'+esc(c.desc)+'</small>'+action+'</div>';}).join('');cbox.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>{const r=engine.acceptContract(b.dataset.accept);setOutcome(r.ok?'Contrat accepte.':'<span class="warn">'+esc(r.message)+'</span>');render();});cbox.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>{const r=engine.claimContract(b.dataset.claim);setOutcome(r.ok?'<span class="good">Recompense reclamee.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();});const market=$('marketList');market.innerHTML=C.items.map(i=>'<button class="soft" data-buy="'+i.id+'">'+esc(i.name)+' <small>'+engine.marketPrice(i)+' cr.</small></button>').join('');market.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const r=engine.buyItem(b.dataset.buy);setOutcome(r.ok?'<span class="good">Achat: '+esc(r.item.name)+'.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();});}
function renderResearch(s){if(!C.features.factions)return;const box=$('researchList');box.innerHTML=C.research.map(r=>{const locked=r.requiresFlag&&!s.flags[r.requiresFlag];const done=s.research.includes(r.id);return'<div class="module"><strong>'+esc(r.name)+'</strong><small>'+esc(r.desc)+'</small><small>'+r.cost+' donnees</small><button data-research="'+r.id+'" class="soft compact" '+(locked||done?'disabled':'')+'>'+(done?'Recherchee':locked?'Verrouillee':'Rechercher')+'</button></div>';}).join('');box.querySelectorAll('[data-research]').forEach(b=>b.onclick=()=>{const r=engine.unlockResearch(b.dataset.research);setOutcome(r.ok?'<span class="good">Recherche debloquee.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();});}
function renderColony(s){if(!C.features.colony)return;const box=$('colonyBox');if(!s.colony.founded){box.innerHTML='<p>Fonder Nouvelle Aube sur Khepri ou Tau Ceti : 140 credits + 10 donnees.</p><button id="foundColony" class="primary">Fonder la colonie</button>';$('foundColony').onclick=()=>{const r=engine.foundColony();setOutcome(r.ok?'<span class="good">Colonie fondee.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();};return;}box.innerHTML='<div class="progress-line"><span>Population '+s.colony.population+'/'+s.colony.maxPopulation+'</span><span>Morale '+s.colony.morale+'</span><span>Pression '+s.colony.threat+'</span></div><div id="buildingList" class="module-list"></div>';const list=$('buildingList');list.innerHTML=C.colonyBuildings.map(b=>{const done=s.colony.buildings.includes(b.id),cost=engine.colonyCost(b);return'<div class="module"><strong>'+esc(b.name)+'</strong><small>'+esc(b.desc)+'</small><small>'+cost.credits+' cr. + '+cost.data+' data</small><button data-building="'+b.id+'" class="soft compact" '+(done?'disabled':'')+'>'+(done?'Construit':'Construire')+'</button></div>';}).join('');list.querySelectorAll('[data-building]').forEach(b=>b.onclick=()=>{const r=engine.buildColony(b.dataset.building);setOutcome(r.ok?'<span class="good">Batiment construit.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();});}
function renderOutposts(s){if(!C.features.galaxy)return;$('outpostBox').innerHTML='<p>Avant-postes: '+(s.outposts.length?s.outposts.map(esc).join(', '):'aucun')+'</p><p>Cout actuel : '+engine.outpostCost()+' credits + 3 donnees.</p><button id="outpostBtn" class="primary">Etablir ici un avant-poste</button>';$('outpostBtn').onclick=()=>{const r=engine.establishOutpost();setOutcome(r.ok?'<span class="good">Avant-poste etabli.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();};}
function renderLog(s){$('logList').innerHTML=s.log.map(x=>'<div class="log-entry">'+x+'</div>').join('');}
function renderRolls(s){$('lastRoll').textContent=s.lastRoll==null?'-':s.lastRoll;$('lastTotal').textContent=s.lastTotal==null?'-':s.lastTotal;const c=engine.selectedCard();$('activeCard').textContent=c?c.name:'Aucune';$('phase').textContent=s.combat?'Combat':s.mission?'Mission':s.currentEvent?'Evenement':'Exploration';$('destinyBtn').textContent=s.useDestinyNext?'Destin actif (avantage)':'Utiliser Destin';$('destinyBtn').classList.toggle('active',s.useDestinyNext);}
function renderCombat(s){if(!s.combat){$('combatBox').classList.add('hidden');return;}$('combatBox').classList.remove('hidden');$('playerCombat').innerHTML='<h3>'+(s.combat.mode==='space'?'Asterion':'Escouade')+'</h3>'+(s.combat.mode==='space'?'Coque '+s.ship.hull+'/'+s.ship.maxHull+'<br>Boucliers '+s.ship.shield+'/'+s.ship.maxShield:'PV commandant '+s.commander.hp+'/'+s.commander.maxHp)+'<br>PA <strong>'+s.combat.ap+'</strong>';$('enemyCombat').innerHTML='<h3>'+esc(s.combat.enemy)+'</h3>Integrite '+s.combat.hp+'/'+s.combat.maxHp+'<br>Armure '+s.combat.armor+'<br>Attaque +'+s.combat.attack;const box=$('combatActions');box.innerHTML='';[['Tir precis — 1 PA','precise'],['Surcharge — 2 PA','overcharge'],['Analyser — 1 PA','analyze'],['Defense — 1 PA','defend'],['Fin du tour','end']].forEach(it=>{const b=document.createElement('button');b.textContent=it[0];b.onclick=()=>combatAction(it[1]);box.appendChild(b);});}
function renderButtons(s){const lock=!!s.combat||!!s.mission;['exploreBtn','siteBtn','scanBtn','repairBtn','refuelBtn','resupplyBtn','freightBtn','sellDataBtn','restBtn','drawBtn'].forEach(id=>{if($(id))$(id).disabled=lock;});$('siteBtn').classList.toggle('hidden',!C.features.missions);}
function showEvent(e,loc){if(!e){setOutcome('<span class="warn">Aucun evenement.</span>');return;}setScene(e.tag,e.title,e.text,C.images[e.image]||C.images.intro);setOutcome('Secteur: <strong>'+esc(loc.label)+'</strong>. Choisis ton approche.');renderEventChoices(e);}
function renderEventChoices(e){const box=$('eventActions');box.innerHTML='';e.choices.forEach((ch,index)=>{const b=document.createElement('button');b.innerHTML=esc(ch.label)+'<small>'+skillLabels[ch.skill]+' + '+statLabels[ch.attr]+' — DD '+ch.dc+'</small>';b.onclick=()=>{const r=engine.resolveChoice(index);if(!r.ok){setOutcome('<span class="warn">'+esc(r.message)+'</span>');return;}const flags=(r.critical?' <strong>CRITIQUE!</strong>':'')+(r.destinyUsed?' — Destin utilise':'');setOutcome('<span class="'+(r.success?'good':'bad')+'"><strong>'+(r.success?'Reussite':'Echec')+'</strong></span>'+flags+' — '+esc(r.outcome.text)+(r.effects.length?'<br><span class="accent">'+r.effects.map(esc).join(' • ')+'</span>':'')+(r.assist?'<br><small>Assistance: '+esc(r.assist.name)+' (+1)</small>':''));if(r.combatStarted){const s=engine.snapshot();setScene('COMBAT','Affrontement : '+s.combat.enemy,'La menace passe a l attaque.',C.images.battle);box.innerHTML='<button disabled>Combat en cours</button>';}else if(engine.snapshot().mission&&engine.snapshot().currentEvent){showEvent(engine.snapshot().currentEvent,{label:'Mission'});}else{box.innerHTML='';addExploreButton();}render();};box.appendChild(b);});}
function addExploreButton(){const b=document.createElement('button');b.className='primary';b.textContent='Continuer l exploration';b.onclick=exploreCurrent;$('eventActions').appendChild(b);}
function exploreCurrent(){const r=engine.exploreCurrent();if(!r.ok){setOutcome('<span class="warn">'+esc(r.message)+'</span>');return;}showEvent(r.event,r.location);render();}
function combatAction(type){const r=engine.combatAction(type);if(!r.ok){setOutcome('<span class="warn">'+esc(r.message)+'</span>');return render();}if(r.victory){setOutcome('<span class="good"><strong>Victoire.</strong></span> '+esc(r.victory.enemy)+' neutralise. +'+r.victory.credits+' credits, +'+r.victory.data+' donnees.');$('eventActions').innerHTML='';if(engine.snapshot().mission&&engine.snapshot().currentEvent)showEvent(engine.snapshot().currentEvent,{label:'Mission'});else addExploreButton();render();return;}if(r.type==='attack')setOutcome(r.success?'<span class="good">Attaque reussie: '+r.damage+' degats.</span>':'<span class="bad">Attaque manquee.</span>');else if(r.type==='defend')setOutcome('<span class="accent">Defense active.</span>');else if(r.type==='enemy')setOutcome(r.hit?'<span class="bad">Riposte: '+r.damage+' degats.</span>':'<span class="good">Riposte evitee.</span>');render();}
function wire(){$('startBtn').onclick=startGame;$('loadBtn').onclick=loadGame;$('saveBtn').onclick=()=>saveGame(true);$('resetSaveBtn').onclick=()=>{try{localStorage.removeItem(SAVE_KEY);setOutcome('Sauvegarde effacee.');}catch(e){}};['nameInput','originSelect','roleSelect','traitSelect','seedInput'].forEach(id=>$(id).addEventListener((id==='nameInput'||id==='seedInput')?'input':'change',preview));$('exploreBtn').onclick=exploreCurrent;$('siteBtn').onclick=()=>{const r=engine.generateSite();if(r.ok)showEvent(r.event,r.location);else setOutcome('<span class="warn">'+esc(r.message)+'</span>');render();};$('scanBtn').onclick=()=>{const r=engine.scan();setOutcome(!r.ok?'<span class="warn">'+esc(r.message)+'</span>':r.success?'<span class="good">Scan reussi — total '+r.total+'.</span>':'<span class="warn">Scan sans resultat — total '+r.total+'.</span>');render();};$('repairBtn').onclick=()=>{const r=engine.repair();setOutcome(r.ok?'<span class="good">Coque reparee.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();};$('refuelBtn').onclick=()=>{const r=engine.refuel();setOutcome(r.ok?'<span class="good">Carburant recharge.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();};$('resupplyBtn').onclick=()=>{const r=engine.resupply();setOutcome(r.ok?'<span class="good">Fournitures rechargees.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();};$('freightBtn').onclick=()=>{const r=engine.freelance();setOutcome(r.ok?'<span class="good">Mission de fret : +'+r.gain+' credits.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();};$('sellDataBtn').onclick=()=>{const r=engine.sellData();setOutcome(r.ok?'<span class="good">Transmission scientifique : +'+r.gain+' credits.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();};$('restBtn').onclick=()=>{const r=engine.rest();setOutcome('<span class="accent">Repos: +'+(r.heal||0)+' PV.</span>');render();};$('drawBtn').onclick=()=>{const r=engine.manualDraw();setOutcome(r.ok?'Carte piochee.':'<span class="warn">'+esc(r.message)+'</span>');render();};$('destinyBtn').onclick=()=>{const r=engine.toggleDestiny();setOutcome(r.ok?(r.active?'Prochain jet avec avantage.':'Destin desactive.'):'<span class="warn">'+esc(r.message)+'</span>');render();};}
if(C.features.pwa&&'serviceWorker' in navigator&&location.protocol.indexOf('http')===0)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();