(function(){
'use strict';
var C=window.GAME_CONTENT,engine=null,SAVE_KEY='exodus2149_save_v'+(C?C.version:'x');
function $(id){return document.getElementById(id);}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function setImage(node,url){if(!node)return;node.style.display='block';node.onerror=function(){node.style.display='none';};node.src=url;}
function setOutcome(html){$('outcome').innerHTML=html;}
function optionFill(node,obj){node.innerHTML='';Object.keys(obj).forEach(function(k){var o=document.createElement('option');o.value=k;o.textContent=obj[k].label;node.appendChild(o);});}
var statLabels={physique:'Physique',reflexes:'Reflexes',intelligence:'Intelligence',technique:'Technique',presence:'Presence',volonte:'Volonte'};
var skillLabels={pilotage:'Pilotage',combat:'Combat',science:'Science',diplomacy:'Diplomatie',engineering:'Ingenierie',survival:'Survie'};
function bootError(err){var b=$('bootState');b.className='boot error';b.textContent='Erreur: '+((err&&err.message)||err||'inconnue');if(window.console&&console.error)console.error(err);}
function init(){try{
 if(!C||!window.ExodusEngine)throw new Error('content.js ou engine.js non charge');engine=new window.ExodusEngine(C);optionFill($('originSelect'),C.origins);optionFill($('roleSelect'),C.roles);optionFill($('traitSelect'),C.traits);$('seedField').style.display=C.features.seeded?'grid':'none';$('loadBtn').style.display=C.features.persistence?'inline-block':'none';$('resetSaveBtn').style.display=C.features.persistence?'inline-block':'none';$('saveBtn').style.display=C.features.persistence?'inline-block':'none';$('crewSection').style.display=C.features.crew?'block':'none';$('moduleSection').style.display=C.features.modules?'block':'none';$('campaignSection').style.display=C.features.campaign?'block':'none';setImage($('startImage'),C.images.intro);wire();preview();$('bootState').className='boot ok';$('bootState').textContent='Moteur pret';if(new URLSearchParams(location.search).get('autotest')==='1'){startGame();}
 }catch(e){bootError(e);}}
function profile(){return{name:$('nameInput').value.trim()||'Nael Orsini',origin:$('originSelect').value,role:$('roleSelect').value,trait:$('traitSelect').value,seed:C.features.seeded?($('seedInput').value.trim()||'EREBUS-2149'):'AUTO-'+Date.now()};}
function preview(){try{var temp=new window.ExodusEngine(C),c=temp.buildCommander(profile());$('creationSummary').innerHTML='<h2>'+esc(c.name)+'</h2><p><strong>'+esc(c.origin.label)+'</strong> - '+esc(c.role.label)+' - '+esc(c.trait.label)+'</p><p>'+esc(c.origin.desc)+'<br>'+esc(c.role.desc)+'<br>'+esc(c.trait.desc)+'</p><div class="stat-grid">'+Object.keys(c.stats).map(function(k){return'<div class="stat"><b>'+statLabels[k]+'</b><strong>'+c.stats[k]+'</strong></div>';}).join('')+'</div>';}catch(e){bootError(e);}}
function startGame(){engine.newGame(profile());$('startScreen').classList.add('hidden');$('game').classList.remove('hidden');setScene('MISSION','Arrivee dans le systeme d Erebus','Les premieres routes interstellaires sont ouvertes. L Asterion attend ton premier ordre.',C.images.intro);$('eventActions').innerHTML='';addExploreButton();render();autoSave();}
function loadGame(){if(!C.features.persistence)return;try{var raw=localStorage.getItem(SAVE_KEY);if(!raw)return alert('Aucune sauvegarde.');var data=JSON.parse(raw);if(!engine.importState(data))throw new Error('Sauvegarde invalide');$('startScreen').classList.add('hidden');$('game').classList.remove('hidden');setScene('REPRISE','Journal restaure','La campagne reprend exactement a son dernier etat.',C.images.intro);render();}catch(e){bootError(e);}}
function saveGame(showMessage){if(!C.features.persistence||!engine||!engine.state)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(engine.exportState()));if(showMessage)setOutcome('<span class="good">Sauvegarde locale effectuee.</span>');}catch(e){if(showMessage)setOutcome('<span class="warn">Sauvegarde impossible dans ce navigateur.</span>');}}
function autoSave(){if(C.features.persistence)saveGame(false);}
function setScene(tag,title,text,img){$('sceneTag').textContent=tag;$('sceneTitle').textContent=title;$('sceneText').textContent=text;setImage($('sceneImage'),img||C.images.intro);}
function render(){var s=engine.snapshot();renderTop(s);renderCommander(s);renderShip(s);renderDestinations(s);renderCards(s);renderCrew(s);renderModules(s);renderCampaign(s);renderLog(s);renderRolls(s);renderCombat(s);renderButtons(s);if(engine.isDestroyed()){setOutcome('<span class="bad"><strong>L Asterion est detruit.</strong> Recharge ou recommence une campagne.</span>');disableGame();}autoSave();}
function renderTop(s){$('topChips').innerHTML='<span class="chip">Jour '+s.day+'</span><span class="chip">Credits '+s.ship.credits+'</span><span class="chip">Donnees '+s.ship.data+'</span><span class="chip">Reputation '+s.ship.reputation+'</span><span class="chip">Seed '+esc(s.seed)+'</span>';}
function renderCommander(s){$('commanderName').textContent=s.commander.name;$('commanderMeta').textContent=s.commander.origin.label+' - '+s.commander.role.label+' - '+s.commander.trait.label;$('statGrid').innerHTML=Object.keys(s.commander.stats).map(function(k){return'<div class="stat"><b>'+statLabels[k]+'</b><strong>'+s.commander.stats[k]+'</strong></div>';}).join('');$('skillGrid').innerHTML=Object.keys(s.commander.skills).map(function(k){return'<div class="stat"><b>'+skillLabels[k]+'</b><strong>'+s.commander.skills[k]+'</strong></div>';}).join('');}
function renderShip(s){$('hullText').textContent=s.ship.hull+'/'+s.ship.maxHull;$('shieldText').textContent=s.ship.shield+'/'+s.ship.maxShield;$('fuelText').textContent=s.ship.fuel+'/'+s.ship.maxFuel;$('hullBar').style.width=(s.ship.hull/s.ship.maxHull*100)+'%';$('shieldBar').style.width=(s.ship.shield/s.ship.maxShield*100)+'%';$('fuelBar').style.width=(s.ship.fuel/s.ship.maxFuel*100)+'%';$('repairBtn').textContent='Reparer (-'+engine.repairCost()+' cr.)';}
function renderDestinations(s){var list=$('destinationList');list.innerHTML='';C.locations.forEach(function(loc){var b=document.createElement('button');b.className='soft';b.innerHTML=esc(loc.label)+(loc.id===s.locationId?' <small>Position actuelle</small>':'');b.disabled=!!s.combat||s.ship.fuel<1;b.onclick=function(){var r=engine.travel(loc.id);if(!r.ok){setOutcome('<span class="warn">'+esc(r.message)+'</span>');return render();}showEvent(r.event,r.location);render();};list.appendChild(b);});}
function renderCards(s){var list=$('cardList');list.innerHTML='';if(!s.hand.length)list.innerHTML='<div class="crew">Main vide.</div>';s.hand.forEach(function(card){var a=document.createElement('article');a.className='card'+(s.selectedCardUid===card.uid?' active':'');a.innerHTML='<h3>'+esc(card.name)+'</h3><p>'+esc(card.text)+'</p><div class="badges">'+card.tags.map(function(t){return'<span class="badge">'+esc(t)+'</span>';}).join('')+'</div>';a.onclick=function(){engine.selectCard(card.uid);render();};list.appendChild(a);});}
function renderCrew(s){if(!C.features.crew)return;$('crewList').innerHTML=s.crew.map(function(m){return'<div class="crew"><strong>'+esc(m.name)+'</strong><small>'+esc(m.role)+' - '+esc(m.specialty)+'</small><div class="crew-meta"><span>Loyaute '+m.loyalty+'</span><span>Stress '+m.stress+'</span></div></div>';}).join('');}
function renderModules(s){if(!C.features.modules)return;$('moduleList').innerHTML=C.modules.map(function(m){var installed=s.modules.indexOf(m.id)>=0;return'<div class="module"><strong>'+esc(m.name)+'</strong><small>'+esc(m.desc)+'</small><small>'+m.cost+' credits</small><button class="soft" data-module="'+esc(m.id)+'" '+(installed?'disabled':'')+'>'+(installed?'Installe':'Installer')+'</button></div>';}).join('');Array.prototype.forEach.call($('moduleList').querySelectorAll('[data-module]'),function(btn){btn.onclick=function(){var r=engine.installModule(btn.getAttribute('data-module'));setOutcome(r.ok?'<span class="good">Module installe.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();};});}
function renderCampaign(s){if(!C.features.campaign)return;$('campaignBox').innerHTML='<p>'+esc(engine.campaignText())+'</p><p>Progression: donnees '+s.ship.data+' - reputation '+s.ship.reputation+'</p>'+(s.campaign.complete?'<p class="good"><strong>VICTOIRE DE CAMPAGNE</strong></p>':'');}
function renderLog(s){$('logList').innerHTML=s.log.map(function(x){return'<div class="log-entry">'+x+'</div>';}).join('');}
function renderRolls(s){$('lastRoll').textContent=s.lastRoll==null?'-':s.lastRoll;$('lastTotal').textContent=s.lastTotal==null?'-':s.lastTotal;var c=engine.selectedCard();$('activeCard').textContent=c?c.name:'Aucune';$('phase').textContent=s.combat?'Combat':(s.currentEvent?'Evenement':'Exploration');}
function renderCombat(s){if(!s.combat){$('combatBox').classList.add('hidden');return;}$('combatBox').classList.remove('hidden');$('playerCombat').innerHTML='<h3>Asterion</h3>Coque '+s.ship.hull+'/'+s.ship.maxHull+'<br>Boucliers '+s.ship.shield+'/'+s.ship.maxShield+'<br>PA <strong>'+s.combat.ap+'</strong>';$('enemyCombat').innerHTML='<h3>'+esc(s.combat.enemy)+'</h3>Integrite '+s.combat.hp+'/'+s.combat.maxHp+'<br>Attaque +'+s.combat.attack;var box=$('combatActions');box.innerHTML='';[['Tir precis - 1 PA','precise'],['Surcharge - 2 PA','overcharge'],['Analyse - 1 PA','analyze'],['Renforcer boucliers - 1 PA','defend'],['Fin du tour','end']].forEach(function(it){var b=document.createElement('button');b.textContent=it[0];b.onclick=function(){combatAction(it[1]);};box.appendChild(b);});}
function renderButtons(s){var lock=!!s.combat;['exploreBtn','scanBtn','repairBtn','refuelBtn','restBtn','drawBtn'].forEach(function(id){$(id).disabled=lock;});}
function disableGame(){Array.prototype.forEach.call(document.querySelectorAll('#game button'),function(b){b.disabled=true;});}
function showEvent(e,loc){if(!e){setOutcome('<span class="warn">Aucun evenement.</span>');return;}setScene(e.tag,e.title,e.text,C.images[e.image]||C.images.intro);setOutcome('Secteur: <strong>'+esc(loc.label)+'</strong>. Choisis ton approche.');renderEventChoices(e);}
function renderEventChoices(e){var box=$('eventActions');box.innerHTML='';e.choices.forEach(function(ch,index){var b=document.createElement('button');b.innerHTML=esc(ch.label)+'<small>'+skillLabels[ch.skill]+' + '+statLabels[ch.attr]+' - DD '+ch.dc+'</small>';b.onclick=function(){var r=engine.resolveChoice(index);if(!r.ok){setOutcome('<span class="warn">'+esc(r.message)+'</span>');return;}var extra=r.effects.length?'<br><span class="accent">'+r.effects.map(esc).join(' - ')+'</span>':'';var assist=r.assist?'<br><small>Assistance: '+esc(r.assist.name)+' (+1)</small>':'';setOutcome('<span class="'+(r.success?'good':'bad')+'"><strong>'+(r.success?'Reussite':'Echec')+'</strong></span> - '+esc(r.outcome.text)+extra+assist+(r.rerolled?'<br><small>Relance utilisee.</small>':'') );if(r.combatStarted){var s=engine.snapshot();setScene('COMBAT','Affrontement: '+s.combat.enemy,'Une menace active ses systemes d armes.',C.images.battle);box.innerHTML='<button disabled>Combat en cours</button>';}else{box.innerHTML='';addExploreButton();}render();};box.appendChild(b);});}
function addExploreButton(){var b=document.createElement('button');b.className='primary';b.textContent='Continuer l exploration';b.onclick=exploreCurrent;$('eventActions').appendChild(b);}
function exploreCurrent(){var r=engine.exploreCurrent();if(!r.ok){setOutcome('<span class="warn">'+esc(r.message)+'</span>');return;}showEvent(r.event,r.location);render();}
function combatAction(type){var r=engine.combatAction(type);if(!r.ok){setOutcome('<span class="warn">'+esc(r.message)+'</span>');return render();}if(r.victory){setOutcome('<span class="good"><strong>Victoire.</strong></span> '+esc(r.victory.enemy)+' neutralise. +'+r.victory.credits+' credits, +'+r.victory.data+' donnees.');$('eventActions').innerHTML='';addExploreButton();render();return;}if(r.type==='attack')setOutcome(r.success?'<span class="good">Attaque reussie: '+r.damage+' degats.</span>':'<span class="bad">Attaque manquee.</span>');else if(r.type==='defend')setOutcome('<span class="accent">Boucliers +'+r.gain+'.</span>');else if(r.type==='enemy')setOutcome(r.hit?'<span class="bad">Riposte: '+r.damage+' degats.</span>':'<span class="good">Riposte evitee.</span>');render();}
function wire(){$('startBtn').onclick=startGame;$('loadBtn').onclick=loadGame;$('saveBtn').onclick=function(){saveGame(true);};$('resetSaveBtn').onclick=function(){try{localStorage.removeItem(SAVE_KEY);alert('Sauvegarde effacee.');}catch(e){}};['nameInput','originSelect','roleSelect','traitSelect','seedInput'].forEach(function(id){$(id).addEventListener(id==='nameInput'||id==='seedInput'?'input':'change',preview);});$('exploreBtn').onclick=exploreCurrent;$('scanBtn').onclick=function(){var r=engine.scan();setOutcome(r.ok?(r.success?'<span class="good">Scan reussi. Total '+r.total+'.</span>':'<span class="warn">Scan sans resultat. Total '+r.total+'.</span>'):'<span class="warn">'+esc(r.message)+'</span>');render();};$('repairBtn').onclick=function(){var r=engine.repair();setOutcome(r.ok?'<span class="good">Coque reparee.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();};$('refuelBtn').onclick=function(){var r=engine.refuel();setOutcome(r.ok?'<span class="good">Ravitaillement +'+r.gain+'.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();};$('restBtn').onclick=function(){var r=engine.rest();setOutcome(r.ok?'<span class="accent">Repos termine.</span>':'<span class="warn">'+esc(r.message)+'</span>');render();};$('drawBtn').onclick=function(){var r=engine.manualDraw();setOutcome(r.ok?'Carte piochee.':'<span class="warn">'+esc(r.message)+'</span>');render();};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
