(function(){
'use strict';
function clone(v){return JSON.parse(JSON.stringify(v));}
class ExodusEngine{
  constructor(content){this.content=content;this.state=null;this.uid=0;}
  hashSeed(text){let h=2166136261>>>0;const s=String(text||'EREBUS');for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0||1;}
  random(){let x=this.state.rng>>>0;x=(Math.imul(1664525,x)+1013904223)>>>0;this.state.rng=x;return x/4294967296;}
  d20(){return Math.floor(this.random()*20)+1;}
  clamp(v,min,max){return Math.max(min,Math.min(max,v));}
  escape(text){return String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  addLog(html){this.state.log.unshift(html);this.state.log=this.state.log.slice(0,100);}
  snapshot(){return this.state;}
  exportState(){return clone(this.state);}
  importState(saved){if(!saved||!saved.commander||!saved.ship)return false;this.state=clone(saved);this.migrateState();this.uid=this.state.deck.length+this.state.hand.length+this.state.discard.length+500;return true;}
  migrateState(){const s=this.state;s.version=this.content.version;s.commander.level=s.commander.level||1;s.commander.xp=s.commander.xp||0;s.commander.skillPoints=s.commander.skillPoints||0;s.commander.maxHp=s.commander.maxHp||16;s.commander.hp=Math.min(s.commander.hp||s.commander.maxHp,s.commander.maxHp);s.commander.injuries=s.commander.injuries||[];s.inventory=s.inventory||{medkit:1,stimulant:1,field_kit:1};s.ship.supplies=s.ship.supplies==null?12:s.ship.supplies;s.ship.maxSupplies=s.ship.maxSupplies||25;s.destiny=s.destiny==null?2:s.destiny;s.useDestinyNext=!!s.useDestinyNext;s.factions=s.factions||{};s.research=s.research||[];s.contracts=s.contracts||{};s.metrics=s.metrics||{combatsWon:0,choicesSucceeded:0,missionsCompleted:0,contractsCompleted:0};s.mission=s.mission||null;s.completedMissions=s.completedMissions||[];s.colony=s.colony||{founded:false,name:'Nouvelle Aube',population:0,maxPopulation:0,morale:0,threat:0,buildings:[]};s.outposts=s.outposts||[];s.campaign=s.campaign||{stage:0,complete:false,ending:null};s.flags=s.flags||{};s.lastScanDay=s.lastScanDay||0;this.initFactions();this.initContracts();this.refreshProgress();}
  buildCommander(profile){const origin=this.content.origins[profile.origin]||this.content.origins.terre;const role=this.content.roles[profile.role]||this.content.roles.explorateur;const trait=this.content.traits[profile.trait]||this.content.traits.curieux;const c={name:profile.name||'Nael Orsini',origin,role,trait,level:1,xp:0,skillPoints:0,hp:16,maxHp:16,injuries:[],stats:{physique:2,reflexes:2,intelligence:2,technique:2,presence:2,volonte:2},skills:{pilotage:1,combat:1,science:1,diplomacy:1,engineering:1,survival:1}};this.applyBonus(c.stats,origin.stats);this.applyBonus(c.skills,origin.skills);this.applyBonus(c.stats,role.stats);this.applyBonus(c.skills,role.skills);return c;}
  applyBonus(target,bonus){Object.keys(bonus||{}).forEach(k=>target[k]=(target[k]||0)+bonus[k]);}
  instantiateCard(card){this.uid+=1;return Object.assign({},card,{uid:'card_'+this.uid});}
  shuffle(items){const arr=items.slice();for(let i=arr.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]];}return arr;}
  newGame(profile={}){const seed=profile.seed||('EREBUS-'+Date.now());this.uid=0;this.state={version:this.content.version,seed,rng:this.hashSeed(seed),day:1,commander:this.buildCommander(profile),ship:{hull:20,maxHull:20,shield:10,maxShield:10,fuel:9,maxFuel:9,credits:110,data:0,reputation:0,supplies:14,maxSupplies:25},destiny:2,useDestinyNext:false,crew:clone(this.content.crew),inventory:{medkit:1,stimulant:1,field_kit:1},modules:[],research:[],factions:{},contracts:{},locationId:'orbital_ring',visitedLocations:['orbital_ring'],currentEvent:null,lastEventIds:[],mission:null,completedMissions:[],combat:null,deck:[],hand:[],discard:[],selectedCardUid:null,lastRoll:null,lastTotal:null,lastRollDetail:null,lastManualDrawDay:0,lastScanDay:0,metrics:{combatsWon:0,choicesSucceeded:0,missionsCompleted:0,contractsCompleted:0},colony:{founded:false,name:'Nouvelle Aube',population:0,maxPopulation:0,morale:0,threat:0,buildings:[]},outposts:[],campaign:{stage:0,complete:false,ending:null},flags:{firstCombatDamageReduced:false,firstContact:false,fieldKitBonus:0},log:[]};this.initFactions();this.initContracts();const source=this.content.cards.filter(c=>!c.requiresFlag).slice(0,14);for(let k=0;k<2;k++)source.forEach(card=>this.state.deck.push(this.instantiateCard(card)));this.state.deck=this.shuffle(this.state.deck);this.draw(5);this.addLog('Expedition lancee. Seed <strong>'+this.escape(seed)+'</strong>.');this.refreshProgress();return this.snapshot();}
  initFactions(){(this.content.factions||[]).forEach(f=>{if(this.state.factions[f.id]==null)this.state.factions[f.id]=f.start||0;});}
  initContracts(){(this.content.contracts||[]).forEach(c=>{if(!this.state.contracts[c.id])this.state.contracts[c.id]={status:'available',start:null};});}
  updateResource(key,delta){const s=this.state.ship;s[key]=(s[key]||0)+delta;if(key==='hull')s.hull=this.clamp(s.hull,0,s.maxHull);if(key==='shield')s.shield=this.clamp(s.shield,0,s.maxShield);if(key==='fuel')s.fuel=this.clamp(s.fuel,0,s.maxFuel);if(key==='supplies')s.supplies=this.clamp(s.supplies,0,s.maxSupplies);if(['credits','data','reputation'].includes(key))s[key]=Math.max(0,s[key]);}
  changeFaction(id,delta){if(!this.content.features.factions||!id)return;this.state.factions[id]=this.clamp((this.state.factions[id]||0)+delta,-100,100);}
  gainXp(amount){if(!amount)return;const c=this.state.commander;c.xp+=amount;const thresholds=[0,20,55,100,160,235,325];while(c.level<thresholds.length&&c.xp>=thresholds[c.level]){c.level+=1;c.skillPoints+=1;c.maxHp+=2;c.hp=Math.min(c.maxHp,c.hp+4);this.addLog('<strong class="good">Niveau '+c.level+' atteint.</strong> +1 point de competence.');}}
  upgradeSkill(skill){const c=this.state.commander;if(c.skillPoints<1)return{ok:false,message:'Aucun point de competence.'};if(!(skill in c.skills))return{ok:false,message:'Competence inconnue.'};if(c.skills[skill]>=7)return{ok:false,message:'Competence au maximum.'};c.skillPoints-=1;c.skills[skill]+=1;return{ok:true};}
  creditReward(base){return this.state.commander.trait.passive==='more_credits'?Math.round(base*1.1):base;}
  repairCost(){let cost=this.state.commander.trait.passive==='cheap_repairs'?16:22;if(this.state.modules.includes('repair_bay'))cost-=3;return Math.max(10,cost);}
  researchBonus(skill){let b=0;if(skill==='science'&&(this.state.research.includes('advanced_scanners')||this.state.modules.includes('lab_array')))b+=1;if(skill==='combat'&&(this.state.research.includes('combat_algorithms')||this.state.modules.includes('combat_ai')))b+=1;if(skill==='pilotage'&&this.state.research.includes('quantum_nav'))b+=1;if(skill==='diplomacy'&&this.state.flags.firstContact&&this.state.research.includes('xeno_linguistics'))b+=1;return b;}
  selectedCard(){return this.state.hand.find(c=>c.uid===this.state.selectedCardUid)||null;}
  selectCard(uid){this.state.selectedCardUid=this.state.selectedCardUid===uid?null:uid;}
  consumeSelectedCard(){const i=this.state.hand.findIndex(c=>c.uid===this.state.selectedCardUid);if(i<0)return null;const c=this.state.hand.splice(i,1)[0];this.state.discard.push(c);this.state.selectedCardUid=null;return c;}
  cardApplies(card,skill){return !!card&&(card.tags.includes('any')||card.tags.includes(skill))&&(!card.requiresFlag||this.state.flags[card.requiresFlag]);}
  draw(count=1){for(let i=0;i<count;i++){if(this.state.hand.length>=6)break;if(!this.state.deck.length&&this.state.discard.length){this.state.deck=this.shuffle(this.state.discard);this.state.discard=[];}const c=this.state.deck.pop();if(!c)break;this.state.hand.push(c);}}
  manualDraw(){if(this.state.combat)return{ok:false,message:'Combat en cours.'};if(this.state.lastManualDrawDay===this.state.day)return{ok:false,message:'Une seule pioche libre par jour.'};if(this.state.hand.length>=6)return{ok:false,message:'La main est pleine.'};this.state.lastManualDrawDay=this.state.day;this.draw(1);return{ok:true};}
  toggleDestiny(){if(this.state.destiny<1&&!this.state.useDestinyNext)return{ok:false,message:'Aucun de du Destin.'};this.state.useDestinyNext=!this.state.useDestinyNext;return{ok:true,active:this.state.useDestinyNext};}
  injuryPenalty(attr){const inj=this.state.commander.injuries||[];let p=0;if(inj.includes('traumatisme_grave'))p+=1;if(attr==='reflexes'&&inj.includes('entorse'))p+=1;if(attr==='physique'&&(inj.includes('contusion')||inj.includes('blessure_combat')))p+=1;if((attr==='intelligence'||attr==='technique')&&inj.includes('neural'))p+=1;return p;}
  crewAssist(skill){let best=null;for(const m of this.state.crew){if(m.specialtySkill===skill&&m.hp>0&&m.stress<90&&(!best||m.loyalty+m.relation>best.loyalty+best.relation))best=m;}return best;}
  performCheck(skill,attr,dc,opts={}){let card=this.selectedCard(),bonus=0,reroll=false,shieldCard=false,healCard=0,advantage=!!opts.advantage;if(this.cardApplies(card,skill)){card=this.consumeSelectedCard();if(card.type==='bonus')bonus+=card.value;if(card.type==='reroll')reroll=true;if(card.type==='shield')shieldCard=true;if(card.type==='advantage')advantage=true;if(card.type==='heal')healCard=card.value;}if(this.state.flags.fieldKitBonus&&(skill==='engineering'||skill==='survival')){bonus+=this.state.flags.fieldKitBonus;this.state.flags.fieldKitBonus=0;}let destinyUsed=false;if(this.state.useDestinyNext&&this.state.destiny>0){advantage=true;destinyUsed=true;this.state.destiny-=1;this.state.useDestinyNext=false;}const assist=this.crewAssist(skill),assistBonus=assist?(assist.relation>=25?2:1):0;const base=this.state.commander.stats[attr]+this.state.commander.skills[skill]+this.researchBonus(skill)+assistBonus+bonus-this.injuryPenalty(attr);const rollA=this.d20(),rollB=advantage?this.d20():null;let roll=rollB==null?rollA:Math.max(rollA,rollB);let total=roll+base;let critical=roll===20,criticalFail=roll===1;let success=critical||(!criticalFail&&total>=dc);let rerolled=false;if(!success&&reroll){rerolled=true;const r=this.d20();roll=r;total=r+base;critical=r===20;criticalFail=r===1;success=critical||(!criticalFail&&total>=dc);}this.state.lastRoll=roll;this.state.lastTotal=total;this.state.lastRollDetail={rollA,rollB,roll,total,base,dc,critical,criticalFail,destinyUsed};if(assist){assist.stress=this.clamp(assist.stress+(success?1:4),0,100);assist.loyalty=this.clamp(assist.loyalty+(success?1:0),0,100);}if(healCard)this.healCommander(healCard);if(critical)this.state.destiny=Math.min(3,this.state.destiny+1);return{success,roll,total,dc,critical,criticalFail,rerolled,assist,usedCard:card,shieldCard,destinyUsed};}
  healCommander(amount){const before=this.state.commander.hp;this.state.commander.hp=this.clamp(before+amount,0,this.state.commander.maxHp);return this.state.commander.hp-before;}
  injureCommander(amount,injury){if(amount<0)amount=-amount;this.state.commander.hp=this.clamp(this.state.commander.hp-amount,0,this.state.commander.maxHp);if(injury&&amount>=3&&!this.state.commander.injuries.includes(injury))this.state.commander.injuries.push(injury);if(this.state.commander.hp<=0){this.state.commander.hp=1;if(!this.state.commander.injuries.includes('traumatisme_grave'))this.state.commander.injuries.push('traumatisme_grave');this.addLog('<span class="bad">Le commandant frôle la mort et doit etre evacue.</span>');}}
  useItem(id){const n=this.state.inventory[id]||0;if(n<1)return{ok:false,message:'Objet indisponible.'};const item=this.content.items.find(x=>x.id===id);if(!item)return{ok:false,message:'Objet inconnu.'};this.state.inventory[id]-=1;if(item.type==='heal')this.healCommander(item.value);if(item.type==='stress')this.state.crew.forEach(m=>m.stress=this.clamp(m.stress-item.value,0,100));if(item.type==='check')this.state.flags.fieldKitBonus=item.value;if(item.type==='fuel')this.updateResource('fuel',item.value);if(item.type==='supplies')this.updateResource('supplies',item.value);return{ok:true,item};}
  addItem(id,count=1){this.state.inventory[id]=(this.state.inventory[id]||0)+count;}
  advanceDay(days=1){for(let d=0;d<days;d++){this.state.day+=1;this.applyColonyProduction();}}
  travelCost(loc){let c=loc.fuel||1;if(this.state.research.includes('efficient_drive'))c=Math.max(1,c-1);return c;}
  availableLocations(){return this.content.locations.filter(loc=>{if(loc.tier>this.content.features.maxTier)return false;if(loc.requiresFlag&&!this.state.flags[loc.requiresFlag])return false;if(loc.requiresStage!=null&&this.state.campaign.stage<loc.requiresStage)return false;return true;});}
  activeEvents(locationId){const pool=this.content.events[locationId]||[];return pool.filter(e=>e.tier<=this.content.features.maxTier);}
  pickEvent(locationId){if(locationId==='echo_anomaly'&&!this.state.flags.firstContact&&this.state.campaign.stage>=2&&this.state.ship.data>=12)return clone(this.content.specialEvents.firstContact);if(this.content.features.galaxy&&locationId==='luyten_relay'&&this.state.campaign.stage>=5&&!this.state.campaign.complete&&this.state.outposts.length>=1&&this.state.ship.data>=20)return clone(this.content.specialEvents.finalCouncil);const pool=this.activeEvents(locationId);if(!pool.length)return null;const recent=this.state.lastEventIds.slice(0,2);let candidates=pool.filter(e=>!recent.includes(e.id));if(!candidates.length)candidates=pool;const e=clone(candidates[Math.floor(this.random()*candidates.length)]);this.state.lastEventIds.unshift(e.id);this.state.lastEventIds=this.state.lastEventIds.slice(0,5);return e;}
  travel(locationId){if(this.state.combat||this.state.mission)return{ok:false,message:'Impossible pendant un combat ou une mission.'};const loc=this.availableLocations().find(x=>x.id===locationId);if(!loc)return{ok:false,message:'Destination verrouillee.'};const cost=this.travelCost(loc);if(this.state.ship.fuel<cost)return{ok:false,message:'Carburant insuffisant.'};this.updateResource('fuel',-cost);this.advanceDay(1);this.state.locationId=locationId;if(!this.state.visitedLocations.includes(locationId))this.state.visitedLocations.push(locationId);this.state.currentEvent=this.pickEvent(locationId);this.addLog('Voyage vers <strong>'+loc.label+'</strong> (-'+cost+' carburant).');this.refreshProgress();this.refreshContracts();return{ok:true,event:this.state.currentEvent,location:loc,cost};}
  exploreCurrent(){if(this.state.combat||this.state.mission)return{ok:false,message:'Combat ou mission en cours.'};if(this.state.ship.supplies<1)return{ok:false,message:'Fournitures insuffisantes.'};this.updateResource('supplies',-1);this.advanceDay(1);this.state.currentEvent=this.pickEvent(this.state.locationId);const loc=this.content.locations.find(x=>x.id===this.state.locationId);this.refreshProgress();return{ok:true,event:this.state.currentEvent,location:loc};}
  generateSite(){if(!this.content.features.missions)return{ok:false,message:'Sites proceduraux disponibles en v1.7.'};if(this.state.combat||this.state.mission)return{ok:false,message:'Action impossible maintenant.'};if(this.state.ship.supplies<2)return{ok:false,message:'Il faut 2 fournitures.'};this.updateResource('supplies',-2);this.advanceDay(1);const env=['grotte de glace','station brisee','cratere magnetique','temple machine'][Math.floor(this.random()*4)];const hazard=['radiations','effondrements','drones dormants','champ electrostatique'][Math.floor(this.random()*4)];const reward=1+Math.floor(this.random()*3);this.state.currentEvent={id:'proc_'+this.state.day+'_'+Math.floor(this.random()*9999),tag:'SITE PROCEDURAL',title:'Site : '+env,image:'ruins',text:'Le site combine '+env+' et '+hazard+'. La seed determine sa configuration.',choices:[{label:'Etudier prudemment',skill:'science',attr:'intelligence',dc:14+reward,success:{text:'Le site livre ses secrets.',data:reward+1,credits:10*reward,xp:6+reward},fail:{text:'Le site resiste a l exploration.',commanderHp:-reward,stressCrew:2,xp:2}},{label:'Forcer le passage',skill:'survival',attr:'reflexes',dc:13+reward,success:{text:'L equipe atteint le coeur du site.',credits:20*reward,supplies:reward,xp:6+reward},fail:{text:'Le passage devient dangereux.',commanderHp:-(reward+1),supplies:-1,xp:2}}]};return{ok:true,event:this.state.currentEvent,location:this.content.locations.find(x=>x.id===this.state.locationId)};}
  resolveChoice(index){const e=this.state.currentEvent;if(!e||!e.choices[index]||this.state.combat)return{ok:false,message:'Choix indisponible.'};const choice=e.choices[index];const check=this.performCheck(choice.skill,choice.attr,choice.dc);const outcome=clone(check.success?choice.success:choice.fail);const effects=this.applyOutcome(outcome,{success:check.success,heroic:!!choice.heroic,shieldCard:check.shieldCard,skill:choice.skill,critical:check.critical});if(check.success)this.state.metrics.choicesSucceeded+=1;this.gainXp(outcome.xp|| (check.success?4:1));this.addLog('<span class="'+(check.success?'good':'bad')+'">'+(check.success?'Reussite':'Echec')+'</span> : '+outcome.text);this.draw(1);this.handleMissionOutcome(outcome);if(outcome.combat)this.startCombat(outcome.combat);else if(!this.state.mission)this.state.currentEvent=null;this.refreshProgress();this.refreshContracts();return{ok:true,...check,outcome,effects,combatStarted:!!outcome.combat,mission:this.state.mission};}
  applyOutcome(outcome,ctx){const effects=[];for(const key of ['credits','data','reputation','supplies','fuel','hull','shield'])if(outcome[key]){let amount=outcome[key];if(key==='credits'&&amount>0)amount=this.creditReward(amount);this.updateResource(key,amount);effects.push((amount>0?'+':'')+amount+' '+key);}if(outcome.commanderHp){this.injureCommander(Math.abs(outcome.commanderHp),outcome.injury);effects.push(outcome.commanderHp+' PV');}if(outcome.stressCrew)this.state.crew.forEach(m=>m.stress=this.clamp(m.stress+outcome.stressCrew,0,100));if(outcome.crewRelation){const m=this.state.crew.find(x=>x.id===outcome.crewRelation.id);if(m)m.relation=this.clamp(m.relation+outcome.crewRelation.delta,-100,100);}if(outcome.item){this.addItem(outcome.item,1);effects.push('+1 '+outcome.item);}if(outcome.faction)this.changeFaction(outcome.faction.id,outcome.faction.delta);if(outcome.firstContact){this.state.flags.firstContact=true;this.changeFaction('xeno',2);this.unlockFlagCards();this.addLog('<strong class="good">PREMIER CONTACT ETABLI.</strong>');}if(outcome.ending){this.state.campaign.ending=outcome.ending;this.state.campaign.complete=true;this.addLog('<strong class="good">Fin de campagne : '+outcome.ending+'.</strong>');}if(ctx.critical&&ctx.success){this.updateResource('data',1);effects.push('+1 data critique');}return effects;}
  unlockFlagCards(){const existing=new Set([...this.state.deck,...this.state.hand,...this.state.discard].map(c=>c.id));this.content.cards.filter(c=>c.requiresFlag&&this.state.flags[c.requiresFlag]&&!existing.has(c.id)).forEach(c=>this.state.discard.push(this.instantiateCard(c)));}
  availableMissions(){if(!this.content.features.missions)return[];return this.content.missions.filter(m=>m.tier<=this.content.features.maxTier&&!this.state.completedMissions.includes(m.id)&&this.missionUnlocked(m));}
  missionUnlocked(m){const u=m.unlock||{};if(u.data&&this.state.ship.data<u.data)return false;if(u.visited&&!this.state.visitedLocations.includes(u.visited))return false;if(u.flag&&!this.state.flags[u.flag])return false;return true;}
  startMission(id){if(!this.content.features.missions)return{ok:false,message:'Missions indisponibles.'};if(this.state.combat||this.state.mission)return{ok:false,message:'Une action majeure est deja en cours.'};const m=this.availableMissions().find(x=>x.id===id);if(!m)return{ok:false,message:'Mission verrouillee.'};if(this.state.ship.supplies<2)return{ok:false,message:'Il faut 2 fournitures.'};this.updateResource('supplies',-2);this.state.mission={id:m.id,step:0};this.state.currentEvent=clone(m.steps[0]);this.addLog('Mission lancee : <strong>'+m.title+'</strong>.');return{ok:true,event:this.state.currentEvent,mission:m};}
  handleMissionOutcome(outcome){if(!this.state.mission)return;if(outcome.missionComplete){const id=this.state.mission.id;if(!this.state.completedMissions.includes(id))this.state.completedMissions.push(id);this.state.metrics.missionsCompleted+=1;this.state.mission=null;this.state.currentEvent=null;this.addLog('<strong class="good">Mission terminee.</strong>');return;}if(outcome.missionAdvance){const m=this.content.missions.find(x=>x.id===this.state.mission.id);this.state.mission.step+=1;if(m&&m.steps[this.state.mission.step])this.state.currentEvent=clone(m.steps[this.state.mission.step]);else{this.state.completedMissions.push(m.id);this.state.metrics.missionsCompleted+=1;this.state.mission=null;this.state.currentEvent=null;}}}
  abandonMission(){if(!this.state.mission)return{ok:false,message:'Aucune mission.'};this.addLog('Mission abandonnee.');this.state.mission=null;this.state.currentEvent=null;return{ok:true};}
  startCombat(data){this.state.combat={enemy:data.enemy,mode:data.mode||'space',hp:data.hp,maxHp:data.hp,attack:data.attack||4,armor:data.armor||0,ap:3,analyzed:false,guard:false,rewardCredits:data.rewardCredits||0,rewardData:data.rewardData||0};this.state.flags.firstCombatDamageReduced=false;this.addLog('Combat contre <strong>'+data.enemy+'</strong> ('+this.state.combat.mode+').');}
  combatAction(type){const c=this.state.combat;if(!c)return{ok:false,message:'Aucun combat.'};if(type==='end')return this.enemyTurn(false);if(type==='defend'){if(c.ap<1)return{ok:false,message:'PA insuffisants.'};c.ap-=1;c.guard=true;const gain=c.mode==='space'?2:0;if(gain)this.updateResource('shield',gain);if(c.ap<=0)return{ok:true,type:'defend',gain,enemy:this.enemyTurn(false)};return{ok:true,type:'defend',gain};}const cfg={precise:{cost:1,skill:'combat',attr:'reflexes',dc:12,damage:5},overcharge:{cost:2,skill:'combat',attr:'reflexes',dc:14,damage:9},analyze:{cost:1,skill:'science',attr:'intelligence',dc:12,damage:3}}[type];if(!cfg||c.ap<cfg.cost)return{ok:false,message:'PA insuffisants.'};c.ap-=cfg.cost;const check=this.performCheck(cfg.skill,cfg.attr,cfg.dc,{advantage:c.analyzed&&type!=='analyze'});let damage=0;if(check.success){damage=Math.max(1,cfg.damage+(check.critical?4:0)+Math.floor(this.random()*3)-c.armor);c.hp=Math.max(0,c.hp-damage);if(type==='analyze')c.analyzed=true;}this.gainXp(check.success?2:1);if(c.hp<=0)return{ok:true,type:'attack',...check,damage,victory:this.finishCombat()};let enemy=null;if(c.ap<=0)enemy=this.enemyTurn(check.shieldCard);return{ok:true,type:'attack',...check,damage,enemy};}
  enemyTurn(shieldCard){const c=this.state.combat;if(!c)return{ok:false,message:'Aucun combat.'};const roll=this.d20(),total=roll+c.attack,hit=roll===20||total>=12;let damage=0;if(hit){damage=3+Math.floor(this.random()*4)+(roll===20?2:0);if(this.state.commander.trait.passive==='first_hit_resist'&&!this.state.flags.firstCombatDamageReduced){damage=Math.max(0,damage-1);this.state.flags.firstCombatDamageReduced=true;}if(shieldCard)damage=Math.max(0,damage-2);if(c.guard){damage=Math.max(0,damage-2);c.guard=false;}if(c.mode==='space'){let remaining=damage;if(this.state.ship.shield>0){const absorbed=Math.min(this.state.ship.shield,remaining);this.updateResource('shield',-absorbed);remaining-=absorbed;}if(remaining)this.updateResource('hull',-remaining);}else{this.injureCommander(damage,damage>=5?'blessure_combat':null);}this.state.crew.forEach(m=>m.stress=this.clamp(m.stress+(this.random()<0.35?2:0),0,100));}c.ap=3;return{ok:true,type:'enemy',hit,roll,total,damage};}
  finishCombat(){const c=this.state.combat;const credits=this.creditReward(c.rewardCredits),data=c.rewardData;this.updateResource('credits',credits);this.updateResource('data',data);this.state.metrics.combatsWon+=1;this.gainXp(8);const enemy=c.enemy;this.state.combat=null;if(!this.state.mission)this.state.currentEvent=null;this.refreshProgress();this.refreshContracts();return{enemy,credits,data};}
  repair(){if(this.state.combat)return{ok:false,message:'Impossible en combat.'};if(this.state.ship.hull>=this.state.ship.maxHull)return{ok:false,message:'Coque intacte.'};const cost=this.repairCost();if(this.state.ship.credits<cost)return{ok:false,message:'Credits insuffisants.'};this.updateResource('credits',-cost);this.updateResource('hull',5);return{ok:true,cost};}
  refuel(){if(this.state.combat)return{ok:false,message:'Impossible en combat.'};if(this.state.ship.fuel>=this.state.ship.maxFuel)return{ok:false,message:'Reservoir plein.'};const cost=this.state.locationId==='orbital_ring'?22:32;if(this.state.ship.credits<cost)return{ok:false,message:'Credits insuffisants.'};this.updateResource('credits',-cost);this.updateResource('fuel',4);return{ok:true,cost,gain:4};}
  resupply(){if(this.state.combat)return{ok:false,message:'Impossible en combat.'};if(this.state.ship.supplies>=this.state.ship.maxSupplies)return{ok:false,message:'Stocks pleins.'};const cost=this.state.locationId==='orbital_ring'?18:26;if(this.state.ship.credits<cost)return{ok:false,message:'Credits insuffisants.'};this.updateResource('credits',-cost);this.updateResource('supplies',6);return{ok:true,cost,gain:6};}
  sellData(){if(this.state.combat||this.state.mission)return{ok:false,message:'Impossible maintenant.'};if(this.state.ship.data<1)return{ok:false,message:'Aucune donnee cessible.'};this.updateResource('data',-1);const gain=this.creditReward(18);this.updateResource('credits',gain);return{ok:true,gain};}
  freelance(){if(this.state.combat||this.state.mission)return{ok:false,message:'Impossible maintenant.'};if(this.state.locationId!=='orbital_ring')return{ok:false,message:'Les missions de fret sont disponibles a l Anneau orbital.'};this.advanceDay(1);const gain=this.creditReward(24);this.updateResource('credits',gain);this.state.crew.forEach(m=>m.stress=this.clamp(m.stress+1,0,100));this.addLog('Mission de fret terminee : +'+gain+' credits.');return{ok:true,gain};}
  rest(){if(this.state.combat)return{ok:false,message:'Impossible en combat.'};this.advanceDay(1);this.updateResource('shield',2);const heal=2+(this.state.modules.includes('medbay')?2:0)+(this.state.research.includes('field_medicine')?2:0);this.healCommander(heal);this.state.crew.forEach(m=>{m.stress=this.clamp(m.stress-(8+(this.state.modules.includes('medbay')?4:0)),0,100);m.hp=this.clamp(m.hp+2,0,m.maxHp);});if(this.state.commander.injuries.length&&this.state.commander.hp>=this.state.commander.maxHp*0.75&&this.random()<0.45)this.state.commander.injuries.shift();return{ok:true,heal};}
  scan(){if(this.state.combat)return{ok:false,message:'Impossible en combat.'};if(this.state.lastScanDay===this.state.day)return{ok:false,message:'Un seul scan complet par jour.'};this.state.lastScanDay=this.state.day;const check=this.performCheck('science','intelligence',13);if(check.success){this.updateResource('data',1+(check.critical?1:0));if(this.random()<0.25)this.updateResource('credits',10);this.gainXp(2);}this.refreshProgress();return{ok:true,...check};}
  installModule(id){const m=this.content.modules.find(x=>x.id===id);if(!m)return{ok:false,message:'Module inconnu.'};if(this.state.modules.includes(id))return{ok:false,message:'Deja installe.'};if(this.state.ship.credits<m.cost)return{ok:false,message:'Credits insuffisants.'};this.updateResource('credits',-m.cost);this.state.modules.push(id);if(m.effect==='shield_max'){this.state.ship.maxShield+=3;this.state.ship.shield+=3;}if(m.effect==='fuel_max'){this.state.ship.maxFuel+=2;this.state.ship.fuel+=2;}if(m.effect==='supplies_max'){this.state.ship.maxSupplies+=10;this.state.ship.supplies+=5;}return{ok:true,module:m};}
  marketPrice(item){let price=item.price;const helix=this.state.factions.helix||0;if(this.content.features.factions)price=Math.round(price*(1-Math.max(-20,Math.min(30,helix))*0.003));if(this.state.commander.trait.passive==='cheap_repairs'&&['field_kit','fuel_cell'].includes(item.id))price=Math.round(price*0.9);return Math.max(5,price);}
  buyItem(id){const item=this.content.items.find(x=>x.id===id);if(!item)return{ok:false,message:'Objet inconnu.'};const price=this.marketPrice(item);if(this.state.ship.credits<price)return{ok:false,message:'Credits insuffisants.'};this.updateResource('credits',-price);this.addItem(id,1);return{ok:true,item,price};}
  unlockResearch(id){if(!this.content.features.factions)return{ok:false,message:'Recherche disponible en v1.8.'};const r=this.content.research.find(x=>x.id===id);if(!r)return{ok:false,message:'Recherche inconnue.'};if(this.state.research.includes(id))return{ok:false,message:'Deja recherche.'};if(r.requiresFlag&&!this.state.flags[r.requiresFlag])return{ok:false,message:'Prerequis non atteint.'};if(this.state.ship.data<r.cost)return{ok:false,message:'Donnees insuffisantes.'};this.updateResource('data',-r.cost);this.state.research.push(id);this.refreshProgress();return{ok:true,research:r};}
  acceptContract(id){if(!this.content.features.factions)return{ok:false,message:'Contrats disponibles en v1.8.'};const def=this.content.contracts.find(x=>x.id===id),st=this.state.contracts[id];if(!def||!st||st.status!=='available')return{ok:false,message:'Contrat indisponible.'};const active=Object.values(this.state.contracts).filter(x=>x.status==='active').length;if(active>=2)return{ok:false,message:'Deux contrats actifs maximum.'};st.status='active';st.start={data:this.state.ship.data,reputation:this.state.ship.reputation,combats:this.state.metrics.combatsWon,visited:this.state.visitedLocations.slice()};return{ok:true,contract:def};}
  contractProgress(def,st){if(!st.start)return 0;if(def.type==='data')return Math.max(0,this.state.ship.data-st.start.data);if(def.type==='reputation')return Math.max(0,this.state.ship.reputation-st.start.reputation);if(def.type==='combats')return Math.max(0,this.state.metrics.combatsWon-st.start.combats);if(def.type==='visit')return this.state.visitedLocations.includes(def.target)&&!st.start.visited.includes(def.target)?1:0;return 0;}
  refreshContracts(){if(!this.content.features.factions)return;for(const def of this.content.contracts){const st=this.state.contracts[def.id];if(st&&st.status==='active'&&this.contractProgress(def,st)>=def.goal)st.status='complete';}}
  claimContract(id){const def=this.content.contracts.find(x=>x.id===id),st=this.state.contracts[id];if(!def||!st||st.status!=='complete')return{ok:false,message:'Contrat non reclamable.'};const rw=def.reward||{};if(rw.credits)this.updateResource('credits',rw.credits);if(rw.data)this.updateResource('data',rw.data);if(rw.reputation)this.updateResource('reputation',rw.reputation);if(rw.faction)this.changeFaction(def.faction,rw.faction);st.status='claimed';this.state.metrics.contractsCompleted+=1;this.gainXp(10);this.refreshProgress();return{ok:true,reward:rw};}
  foundColony(){if(!this.content.features.colony)return{ok:false,message:'Colonies disponibles en v1.9.'};if(this.state.campaign.stage<5)return{ok:false,message:'Termine d abord les objectifs diplomatiques et scientifiques.'};if(this.state.colony.founded)return{ok:false,message:'Colonie deja fondee.'};if(!['ash_moon','tau_ceti'].includes(this.state.locationId))return{ok:false,message:'Il faut etre sur Khepri ou Tau Ceti.'};if(this.state.ship.credits<140||this.state.ship.data<10)return{ok:false,message:'Il faut 140 credits et 10 donnees.'};this.updateResource('credits',-140);this.updateResource('data',-10);this.state.colony={founded:true,name:'Nouvelle Aube',population:120,maxPopulation:180,morale:62,threat:10,buildings:[]};this.addLog('<strong class="good">Colonie Nouvelle Aube fondee.</strong>');this.refreshProgress();return{ok:true};}
  colonyCost(b){let credits=b.credits;if(this.state.research.includes('colony_methods'))credits=Math.round(credits*0.9);return{credits,data:b.data};}
  buildColony(id){if(!this.state.colony.founded)return{ok:false,message:'Aucune colonie.'};const b=this.content.colonyBuildings.find(x=>x.id===id);if(!b)return{ok:false,message:'Batiment inconnu.'};if(this.state.colony.buildings.includes(id))return{ok:false,message:'Deja construit.'};const cost=this.colonyCost(b);if(this.state.ship.credits<cost.credits||this.state.ship.data<cost.data)return{ok:false,message:'Ressources insuffisantes.'};this.updateResource('credits',-cost.credits);this.updateResource('data',-cost.data);this.state.colony.buildings.push(id);if(b.effect==='morale'){this.state.colony.morale=this.clamp(this.state.colony.morale+15,0,100);this.state.colony.maxPopulation+=60;}this.refreshProgress();return{ok:true,building:b,cost};}
  applyColonyProduction(){if(!this.state.colony.founded)return;const b=this.state.colony.buildings;if(b.includes('mine'))this.updateResource('credits',8);if(b.includes('farm'))this.updateResource('supplies',3);if(b.includes('lab')&&this.state.day%3===0)this.updateResource('data',1);let rise=2;if(b.includes('defense'))rise=0;this.state.colony.threat=this.clamp(this.state.colony.threat+rise,0,100);if(this.state.colony.threat>=80&&this.state.day%4===0){this.state.colony.morale=this.clamp(this.state.colony.morale-3,0,100);this.addLog('<span class="warn">La pression rivale entame le moral colonial.</span>');}this.state.colony.population=this.clamp(this.state.colony.population+(this.state.colony.morale>=55?1:0),0,this.state.colony.maxPopulation);if(this.state.outposts.length)this.updateResource('credits',this.state.outposts.length*2);}
  outpostCost(){return this.state.colony.buildings.includes('shipyard')?50:65;}
  establishOutpost(){if(!this.content.features.galaxy)return{ok:false,message:'Avant-postes disponibles en v2.0.'};if(this.state.campaign.stage<6)return{ok:false,message:'Developpe d abord une colonie stable.'};if(['orbital_ring','ash_moon'].includes(this.state.locationId))return{ok:false,message:'Choisis un site de frontiere.'};if(this.state.outposts.includes(this.state.locationId))return{ok:false,message:'Avant-poste deja etabli.'};const cost=this.outpostCost();if(this.state.ship.credits<cost||this.state.ship.data<3)return{ok:false,message:'Il faut '+cost+' credits et 3 donnees.'};this.updateResource('credits',-cost);this.updateResource('data',-3);this.state.outposts.push(this.state.locationId);this.addLog('Avant-poste etabli a <strong>'+this.state.locationId+'</strong>.');this.refreshProgress();return{ok:true,cost};}
  refreshProgress(){const s=this.state,f=this.content.features;let stage=0;if(s.ship.data>=6)stage=1;if(stage>=1&&s.visitedLocations.includes('ash_moon')&&s.ship.reputation>=4)stage=2;if(s.flags.firstContact)stage=3;if(f.missions&&s.flags.firstContact&&s.metrics.missionsCompleted>=2)stage=4;if(f.factions&&stage>=4&&s.metrics.contractsCompleted>=2&&s.research.length>=2)stage=5;if(f.colony&&stage>=5&&s.colony.founded&&s.colony.buildings.length>=2)stage=6;if(f.galaxy&&stage>=6&&s.outposts.length>=1)stage=7;if(s.campaign.ending){stage=8;s.campaign.complete=true;}s.campaign.stage=Math.max(s.campaign.stage||0,stage);const level=f.level;if(level===6&&s.flags.firstContact)s.campaign.complete=true;if(level===7&&s.flags.firstContact&&s.metrics.missionsCompleted>=2)s.campaign.complete=true;if(level===8&&s.flags.firstContact&&s.metrics.missionsCompleted>=2&&s.metrics.contractsCompleted>=2&&s.research.length>=2)s.campaign.complete=true;if(level===9&&s.flags.firstContact&&s.metrics.missionsCompleted>=2&&s.metrics.contractsCompleted>=2&&s.research.length>=2&&s.colony.founded&&s.colony.buildings.length>=2)s.campaign.complete=true;}
  campaignText(){const s=this.state,f=this.content.features;if(s.campaign.complete){if(s.campaign.ending)return'Campagne terminee : '+s.campaign.ending+'.';return'Objectif de la version '+this.content.version+' accompli.';}if(!s.flags.firstContact){if(s.ship.data<6)return'Chapitre 1 : collecter 6 donnees.';if(!s.visitedLocations.includes('ash_moon')||s.ship.reputation<4)return'Chapitre 2 : visiter Khepri et atteindre 4 reputation.';return'Chapitre 3 : atteindre 12 donnees puis explorer Echo-7.';}if(f.level===6)return'Premier Contact etabli : objectif v1.6 accompli.';if(f.missions&&s.metrics.missionsCompleted<2)return'Expeditions : terminer 2 missions ('+s.metrics.missionsCompleted+'/2).';if(f.level===7)return'Objectif v1.7 atteint.';if(f.factions&&(s.metrics.contractsCompleted<2||s.research.length<2))return'Influence : 2 contrats et 2 recherches. Contrats '+s.metrics.contractsCompleted+'/2, recherches '+s.research.length+'/2.';if(f.level===8)return'Objectif v1.8 atteint.';if(f.colony&&(!s.colony.founded||s.colony.buildings.length<2))return'Expansion : fonder une colonie et construire 2 batiments.';if(f.level===9)return'Objectif v1.9 atteint.';if(f.galaxy&&s.outposts.length<1)return'Age des Portes : etablir un avant-poste de frontiere.';return'Age des Portes : accumuler 20 donnees puis atteindre Luyten.';}
  isDestroyed(){return this.state.ship.hull<=0;}
}
window.ExodusEngine=ExodusEngine;
})();