(function(){
'use strict';
const D=window.NARRATIVE_CONTENT;let N=null,slide=0;const $=id=>document.getElementById(id);const esc=t=>String(t==null?'':t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ensure(){const e=window.exodusEngine;if(!e||!e.snapshot())return null;if(!N||N.engine!==e)N=new window.ExodusNarrative(e,D);N.ensureState();return N;}
function modal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('narrativeModal').classList.remove('hidden');}
function closeModal(){$('narrativeModal').classList.add('hidden');}
function showGuide(){modal('Guide du commandant','<div class="guide-grid">'+D.guideSections.map(x=>'<section class="guide-card"><h3>'+esc(x.title)+'</h3><p>'+esc(x.body)+'</p></section>').join('')+'</div>');}
function showIntro(){slide=0;renderIntro();}
function renderIntro(){const s=D.introSlides[slide];modal('Introduction','<div class="intro-slide"><span class="tag">'+esc(s.tag)+'</span><h2>'+esc(s.title)+'</h2><p>'+esc(s.text)+'</p><div class="intro-progress">'+D.introSlides.map((_,i)=>'<span class="'+(i===slide?'on':'')+'"></span>').join('')+'</div><div class="button-row"><button id="introPrev" class="soft" '+(slide===0?'disabled':'')+'>Précédent</button><button id="introNext" class="primary">'+(slide===D.introSlides.length-1?'Commencer':'Suivant')+'</button></div></div>');$('introPrev').onclick=()=>{slide=Math.max(0,slide-1);renderIntro();};$('introNext').onclick=()=>{if(slide<D.introSlides.length-1){slide++;renderIntro();}else{try{localStorage.setItem('exodus_intro_seen_'+D.version,'1');}catch(e){}closeModal();}};}
function maybeFirstIntro(){try{if(!localStorage.getItem('exodus_intro_seen_'+D.version))showIntro();}catch(e){showIntro();}}
function relBars(r){const labels={trust:'Confiance',friendship:'Amitié',respect:'Respect',fear:'Peur',attraction:'Attirance',resentment:'Ressentiment'};return Object.keys(labels).map(k=>'<div class="rel-row"><span>'+labels[k]+'</span><i><b style="width:'+Math.max(0,Math.min(100,r[k]||0))+'%"></b></i><strong>'+Math.round(r[k]||0)+'</strong></div>').join('');}
function enhanceCrew(){const n=ensure();if(!n||!$('crewList'))return;const s=n.state(),box=$('crewList');box.innerHTML=s.crew.map(m=>{const p=D.crewProfiles[m.id],r=n.relation(m.id),available=n.availableConversations(m.id);const portrait=p?'<img class="crew-portrait" src="'+esc(p.portrait)+'" alt="'+esc(m.name)+'" onerror="this.style.display=\'none\'">':'';return'<article class="crew narrative-crew">'+portrait+'<div class="crew-main"><strong>'+esc(m.name)+'</strong><small>'+esc(m.role)+(p?' · '+p.age+' ans · '+esc(p.origin):'')+'</small><div class="crew-meta"><span>PV '+m.hp+'/'+m.maxHp+'</span><span>Stress '+m.stress+'</span><span>Confiance '+Math.round(r.trust)+'</span><span>Respect '+Math.round(r.respect)+'</span></div><button class="soft compact" data-talk="'+m.id+'">Parler'+(available.length?' · '+available.length:'')+'</button><button class="soft compact" data-profile="'+m.id+'">Profil</button></div></article>';}).join('');box.querySelectorAll('[data-talk]').forEach(b=>b.onclick=()=>showTalk(b.dataset.talk));box.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>showProfile(b.dataset.profile));}
function showProfile(id){const n=ensure(),p=D.crewProfiles[id],r=n.relation(id),ns=n.ensureState(),secret=ns.secretLevels[id]||0,arc=D.arcs[id];modal(p.name,'<div class="profile-head"><img src="'+esc(p.portrait)+'" alt=""><div><h2>'+esc(p.role)+'</h2><p>'+esc(p.origin)+' · '+p.age+' ans</p><p>'+p.traits.map(esc).join(' · ')+'</p></div></div><p><strong>Objectif :</strong> '+esc(p.goal)+'</p><p><strong>Peur :</strong> '+esc(p.fear)+'</p><div class="relations">'+relBars(r)+'</div><h3>Arc personnel</h3><p>'+esc(arc.title)+' · '+(ns.arcProgress[id]||0)+'/'+arc.steps+'</p><h3>Ce que tu sais</h3><p>'+(secret?esc(p.secretLevels[Math.min(secret-1,p.secretLevels.length-1)]):'<span class="muted">Ses secrets restent fermés.</span>')+'</p>');}
function showTalk(id){const n=ensure(),p=D.crewProfiles[id],scenes=n.availableConversations(id);if(!scenes.length){modal(p.name,'<p>'+esc(p.name)+' n’a rien de nouveau à dire pour le moment. Les conversations se débloquent avec le temps, la confiance et les événements.</p>');return;}modal('Conversation · '+p.name,'<p class="muted">Choisis une scène disponible.</p><div class="button-list">'+scenes.map(s=>'<button data-scene="'+s.id+'"><strong>'+esc(s.title)+'</strong><small>'+esc(s.text.slice(0,100))+'…</small></button>').join('')+'</div>');$('modalBody').querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>openScene(b.dataset.scene));}
function openScene(id){const n=ensure(),r=n.startConversation(id);if(!r.ok)return;const s=r.scene;modal(D.crewProfiles[s.crew].name,'<div class="dialogue"><h2>'+esc(s.title)+'</h2><p>'+esc(s.text)+'</p><div class="event-actions">'+s.choices.map((c,i)=>'<button data-choice="'+i+'">'+esc(c.text)+'</button>').join('')+'</div></div>');$('modalBody').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const out=n.chooseConversation(id,Number(b.dataset.choice));modal(D.crewProfiles[s.crew].name,'<div class="dialogue"><p>'+esc(out.choice.response)+'</p><p class="accent">La relation a changé. Ces conséquences sont sauvegardées.</p><button id="dialogueClose" class="primary">Continuer</button></div>');$('dialogueClose').onclick=()=>{closeModal();renderNarrative();};});}
function renderHub(){const n=ensure();if(!n||!$('narrativeStatus'))return;const ns=n.ensureState();$('narrativeStatus').innerHTML='<p><strong>Tension narrative :</strong> '+ns.tension+'/100</p><p><strong>Scènes vécues :</strong> '+ns.seenScenes.length+'</p><p><strong>Chronologie :</strong> '+ns.timeline.length+' entrées</p>';$('narrativeActions').innerHTML='<button id="introReplay" class="soft">Revoir l’introduction</button><button id="guideOpen" class="soft">Ouvrir le guide</button>';$('introReplay').onclick=showIntro;$('guideOpen').onclick=showGuide;}
function renderExpeditions(){const sec=$('expeditionSection');if(!sec)return;sec.classList.toggle('hidden',!D.features.expeditions);if(!D.features.expeditions)return;const n=ensure(),st=n.expeditionState(),box=$('expeditionBox');if(st){box.innerHTML='<div class="threat"><span>Menace '+st.expedition.threat+'/10</span><i><b style="width:'+(st.expedition.threat*10)+'%"></b></i></div><h4>'+esc(st.site.title)+' · '+esc(st.node.title)+'</h4><p>'+esc(st.node.text)+'</p><div class="event-actions">'+st.node.choices.map((c,i)=>'<button data-expchoice="'+i+'">'+esc(c.label)+'<small>'+esc(c.skill)+' + '+esc(c.attr)+' · DD '+c.dc+'</small></button>').join('')+'</div><button id="abortExpedition" class="danger compact">Abandonner</button>';box.querySelectorAll('[data-expchoice]').forEach(b=>b.onclick=()=>{const r=n.expeditionChoice(Number(b.dataset.expchoice));if(r.complete)modal('Fin d’expédition','<p>'+esc(r.text)+'</p><p class="accent">'+esc(r.reason)+'</p><button id="expDone" class="primary">Retour au vaisseau</button>');else modal(r.node.title,'<p>'+esc(r.text)+'</p><p>Menace : '+r.threat+'/10</p><button id="expNext" class="primary">Continuer</button>');const btn=$('expDone')||$('expNext');if(btn)btn.onclick=()=>{closeModal();renderNarrative();};});$('abortExpedition').onclick=()=>{n.abortExpedition();renderNarrative();};return;}
 const sites=n.availableExpeditions();box.innerHTML='<p class="muted">Choisis un site et trois compagnons. Une expédition coûte 2 fournitures.</p><div class="team-select">'+Object.values(D.crewProfiles).map(p=>'<label><input type="checkbox" data-team="'+Object.keys(D.crewProfiles).find(k=>D.crewProfiles[k]===p)+'"> '+esc(p.name)+'</label>').join('')+'</div><div class="module-list">'+sites.map(x=>'<div class="module"><strong>'+esc(x.title)+'</strong><small>'+esc(x.desc)+'</small><button data-expedition="'+x.id+'" class="soft compact">Lancer</button></div>').join('')+'</div>';box.querySelectorAll('[data-expedition]').forEach(b=>b.onclick=()=>{const team=[...box.querySelectorAll('[data-team]:checked')].map(x=>x.dataset.team);const r=n.startExpedition(b.dataset.expedition,team);if(!r.ok)modal('Expédition','<p class="warn">'+esc(r.message)+'</p>');renderNarrative();});}
function renderSocial(){const sec=$('socialSection');if(!sec)return;sec.classList.toggle('hidden',!D.features.social);if(!D.features.social)return;const n=ensure(),ns=n.ensureState(),box=$('socialBox');box.innerHTML='<div class="button-row"><button id="networkPulse" class="soft compact">Actualiser le Réseau</button></div><h4>Actualités</h4>'+((ns.news||[]).slice(0,3).map(x=>'<div class="news-item"><strong>'+esc(x.title)+'</strong><small>Jour '+x.day+'</small><p>'+esc(x.text)+'</p></div>').join('')||'<p class="muted">Aucune actualité récente.</p>')+'<h4>Rumeurs</h4>'+((ns.rumors||[]).slice(0,3).map(x=>'<div class="news-item"><small>Jour '+x.day+' · '+esc(x.truth)+'</small><p>'+esc(x.text)+'</p></div>').join('')||'<p class="muted">Aucune rumeur.</p>')+'<h4>Contacts</h4><div class="module-list">'+D.npcs.slice(0,6).map(p=>'<div class="module"><strong>'+esc(p.name)+'</strong><small>'+esc(p.role)+' · '+esc(p.faction)+' · relation '+(ns.npcRelations[p.id]||0)+'</small><button data-npc="'+p.id+'" class="soft compact">Rencontrer</button></div>').join('')+'</div>';$('networkPulse').onclick=()=>{n.socialPulse(true);renderNarrative();};box.querySelectorAll('[data-npc]').forEach(b=>b.onclick=()=>{const r=n.npcAction(b.dataset.npc,'meet');modal('Réseau','<p>'+esc(r.text)+'</p><button id="socialDone" class="primary">Continuer</button>');$('socialDone').onclick=()=>{closeModal();renderNarrative();};});}
function renderLegacy(){const sec=$('legacySection');if(!sec)return;sec.classList.toggle('hidden',!D.features.legacy);if(!D.features.legacy)return;const n=ensure(),ns=n.ensureState(),box=$('legacyBox');const leg=ns.legacy;box.innerHTML='<div class="legacy-grid"><span>Explorateur <b>'+leg.explorer+'</b></span><span>Diplomate <b>'+leg.diplomat+'</b></span><span>Scientifique <b>'+leg.scientist+'</b></span><span>Conquérant <b>'+leg.conqueror+'</b></span><span>Protecteur <b>'+leg.protector+'</b></span></div><h4>Chronique</h4><div class="chronicle">'+(ns.chronicle.slice(0,8).map(esc).map(x=>'<p>'+x+'</p>').join('')||'<p class="muted">La chronique commence avec tes premières décisions.</p>')+'</div><h4>Mémorial</h4>'+(ns.memorial.length?ns.memorial.map(x=>'<p>'+esc(x.name)+' · jour '+x.day+'</p>').join(''):'<p class="muted">Aucun nom inscrit.</p>');}
function renderDirector(){const sec=$('directorSection');if(!sec)return;sec.classList.toggle('hidden',!D.features.director);if(!D.features.director)return;const n=ensure(),ns=n.ensureState(),box=$('directorBox');box.innerHTML='<div class="threat calm"><span>Tension dramatique '+ns.tension+'/100 · Fils '+Object.keys(ns.threads||{}).length+'</span><i><b style="width:'+ns.tension+'%"></b></i></div><p>Le Directeur narratif surveille les fils ouverts, les promesses, le calme et les crises.</p><button id="directorPulse" class="soft compact">Demander une scène contextuelle</button>';$('directorPulse').onclick=()=>{const ev=n.directorPulse(true);if(!ev){modal('Directeur narratif','<p>Aucune scène pertinente n’est prête. Le système évite volontairement de répéter les mêmes situations.</p>');return;}openDirector(ev);};if(ns.directorEvent)openDirectorBadge(ns.directorEvent);}
function openDirectorBadge(ev){const b=document.createElement('button');b.className='director-alert';b.textContent='Scène narrative : '+ev.title;b.onclick=()=>openDirector(ev);$('directorBox').prepend(b);}
function openDirector(ev){const n=ensure();modal('Directeur narratif · '+ev.title,'<p>'+esc(ev.text)+'</p><div class="event-actions">'+ev.choices.map((c,i)=>'<button data-director="'+i+'">'+esc(c.text)+'</button>').join('')+'</div>');$('modalBody').querySelectorAll('[data-director]').forEach(b=>b.onclick=()=>{n.resolveDirector(Number(b.dataset.director));closeModal();renderNarrative();});}
function renderNarrative(){const n=ensure();if(!n)return;n.tick();enhanceCrew();renderHub();renderExpeditions();renderSocial();renderLegacy();renderDirector();}
function init(){if(!D||!window.ExodusNarrative)return;$('guideBtn').onclick=showGuide;$('introBtn').onclick=showIntro;$('modalClose').onclick=closeModal;$('narrativeModal').onclick=e=>{if(e.target===$('narrativeModal'))closeModal();};window.addEventListener('exodus:render',renderNarrative);maybeFirstIntro();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
